config/routes.rb
FdurLink::Application.routes.draw do
  
  root 'sessions#new'
  
  resources :users do
    resources :projects
  end
  get '/signup', to: 'users#new'

  resources :sessions, only: [:new, :create, :destroy]
  get '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

end

app/models/permission.rb
# == Schema Information
#
# Table name: permissions
#
#  id          :integer          not null, primary key
#  name        :string(255)
#  description :string(255)
#  created_at  :datetime
#  updated_at  :datetime
#

class Permission < ActiveRecord::Base
  has_many :users
end

app/models/project.rb
# == Schema Information
#
# Table name: projects
#
#  id         :integer          not null, primary key
#  content    :string(255)
#  user_id    :integer
#  created_at :datetime
#  updated_at :datetime
#

class Project < ActiveRecord::Base
  belongs_to :user

  validates :content, length: {:maximum => 140}
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  email           :string(255)
#  created_at      :datetime
#  updated_at      :datetime
#  password_digest :string(255)
#  remember_token  :string(255)
#  permission_id   :integer          default(1)
#

class User < ActiveRecord::Base
  has_many :projects
  belongs_to :permission, dependent: :destroy
  has_one :user_detail, dependent: :destroy
  
  before_save {self.email.downcase!}
  before_save :create_remember_token

  has_secure_password
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: {with: VALID_EMAIL_REGEX}, uniqueness: { case_sensitive: false }
  validates :password, presence: true,length:{minimum: 6}
  validates :password_confirmation, presence: true
  
  def name
    self.user_detail.nil? ? nil : self.user_detail.name
  end

  private

    def create_remember_token
      self.remember_token = SecureRandom.urlsafe_base64
    end
end

app/models/user_detail.rb
# == Schema Information
#
# Table name: user_details
#
#  id          :integer          not null, primary key
#  name        :string(255)
#  description :text
#  avatar      :string(255)
#  qqnumber    :string(255)
#  user_id     :integer
#  created_at  :datetime
#  updated_at  :datetime
#

class UserDetail < ActiveRecord::Base
  belongs_to :user

  validates :name, presence: true, length: {maximum: 20}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper

def check_signed_in
  if signed_in?
    nil
  else
    flash[:error] = "Please singin first!"
    redirect_to signin_path
  end
end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :check_signed_in
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  before_action :find_current_user

  def index
    @projects = current_user.projects.all
  end

  def show
  end

  def new
    @project = current_user.projects.build
  end

  def edit
  end

  def create
    @project = current_user.projects.build project_params
    if @project.save
      redirect_to action: :index, notice: 'Project was successfully created.' 
    else
      render action: 'new' 
    end
  end

  def update
    if @project.update(project_params)
      redirect_to [@user,@project], notice: 'Project was successfully updated.' 
    else
      render action: 'edit'
    end
  end

  def destroy
    @project.destroy
    redirect_to user_projects_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:content, :user_id)
    end

    def find_current_user
      @user = current_user
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  layout false

  def new
  end

  def create
  	user = User.find_by_email(params[:session][:email].downcase)
  	if user && user.authenticate(params[:session][:password])
  	  sign_in user
  	  redirect_to user_projects_path current_user
    else
      flash.now[:error] = 'Invalid email/password combination'
      render 'new'
    end
  end
  
  def destroy
  	sign_out
  	redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update]
  before_action :check_signed_in ,except: [:new, :create]

  def index
    @users = User.all
  end

  def show
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)
    if @user.save!
      default_name = user_params[:email].match(/(\A[\w+\-.]+)@[a-z\d\-.]+\.[a-z]+\z/)[1]
      @user.create_user_detail name: default_name
      flash.now[:success] = "welcome to the Fdur"
      sign_in @user
      redirect_to @user, notice: 'Welcome To The Fdur' 
    else
      flash.now[:error] = 'Invalid email/password combination'
      render action: :new
    end
  end

  def update
    if @user.update(user_params)
      flash.now[:success] = 'User was successfully updated.'
      redirect_to @user, notice: 'User was successfully updated.'
    else
      render action: :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to users_url
  end

  private
    def set_user
      @user = current_user
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email,:password,:password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def sign_in user
    cookies.permanent[:remember_token] = user.remember_token
    self.current_user = user
  end

  def current_user= user
    @current_user = user
  end

  def current_user
    @current_user ||= User.find_by_remember_token(cookies[:remember_token])
  end

  def signed_in?
    !current_user.nil?
  end

  def sign_out
    self.current_user = nil
    cookies.delete(:remember_token)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FdurLink</title>
  <%= stylesheet_link_tag  "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<header style="background: pink">
  <%= link_to "Users", '#' %>
  <%= link_to "Settings", '#'%>
  <%= link_to "Sign out", signout_path, method:"delete"%>
  <%= link_to "Profile", current_user %>
</header>
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>"><%= value %></div>
<% end %>

<%= yield %>

</body>
</html>

app/views/projects/_form.html.erb
<%= form_for [@user, @project] do |f| %>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_field :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render 'form' %>

<%= link_to 'Show', [@user, @project] %> |
<%= link_to 'Back', user_projects_path %>

app/views/projects/index.html.erb
<h1>Listing projects</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>User</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.content %></td>
        <td><%= project.user_id %></td>
        <td><%= link_to 'Show', @project %></td>
        <td><%= link_to 'Edit', edit_user_project_path(@user,project) %></td>
        <td><%= link_to 'Destroy', [@user,project], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Project', new_user_project_path %>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render 'form' %>

<%= link_to 'Back', user_projects_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @project.content %>
</p>

<p>
  <strong>User:</strong>
  <%= @project.user_id %>
</p>

<%= link_to 'Edit', edit_user_project_path(@user,@project) %> |
<%= link_to 'Back', user_projects_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
    <%= f.label :email %><br>
    <%= f.text_field :email %><br>
    <%= f.label :password %><br>
    <%= f.password_field :password %><br>
    <%= f.label :password_confirmation,"Confirmation"%><br>
    <%= f.password_field :password_confirmation%><br>
    <%= f.submit "Create my account" %>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>